#spring:
##  datasource:
##    driverClassName: org.h2.Driver
##    url: jdbc:h2:/opt/rss-api/data/hohistar-con-data
##    username: sa
##    password:
##  jpa:
##    database: H2
##    generate-ddl: true
##    show-sql: true
##    hibernate:
##      ddl-auto: create-drop
##  h2:
##    console:
##      enabled: true
##      path: /api/h2
##      settings:
##        web-allow-others: true

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥(自定义)
  secret: 6F3931D35F0395DF82B032B8019AC57D
  # 令牌有效期（默认30分钟）
  expireTime: 30